### ISSUE TITLE
界面很牛，但是小问题很多，有几个建议

### ISSUE THREAD

**Issue by lovewestwind** [asdwsx1234/vue-douyin#4]
算一个技术覆盖的项目，dy的界面都撸出来了，但是真正用起来还是有点小问题

几个问题：
需要手动点击播放
进入下页，上页继续播放
播放完不能自动下页或者循环

还有这个外键，让人头疼
没写过node.js，是因为sequelize不能设置吗
也导致了这个字符集编码，init的脚本不会自动设置，会使用默认的当前数据库字符集

建议：
播放器可以用dplayer试试，这样视频链接能支持的多些
这外键效率太低了，建议去掉
list翻到一半之后可以开始预加载下一页这样的机制
少一根播放的进度条

**Comment by ChineseHero** [comment]
手机适配也有问题。

**Comment by asdwsx1234** [comment]
别太在意，毕竟是个毕业设计项目，现在看自己的代码真是不堪入目。
